spring:
  application:
    name: hhplus
#  profiles:
#    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/hhplus
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      retries: 4
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retry.backoff.ms: 1000
    listener:
      type: batch
      ack-mode: manual

